name: Publish bundle to charm store

on:
  - push

jobs:
  build:
    name: Publish bundle
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install charm --classic
        sudo snap install juju-helpers --classic --channel edge

    - name: Publish bundle
      env:
        CHARMSTORE_CREDENTIAL: ${{ secrets.CHARMSTORE_CREDENTIAL }}
      run: |
        set -eux
        echo $CHARMSTORE_CREDENTIAL > ~/.go-cookies
        juju-bundle publish \
            --url cs:~notebook-charmers/jupyter \
            --publish-charms \
            --publish-namespace notebook-charmers
